### ISSUE TITLE
Feature request: Folder notes + track the current file

### ISSUE THREAD

**Issue by tmargosiak** [XuQuan-nikkkki/FolderFile-Splitter-Plugin#19]
Two missing features to switch completely to your plugin:

1. folder notes - after clicking on the folder that has a folder note the note should be automatically displayed and the folder note should be hidden from the list of notes in the folder.
2. track the currently selected note

**Comment by XuQuan-nikkkki** [comment]
Thanks for your feedback.
1. Folder notes are already on my roadmap, so that’s definitely something I plan to add.
2. For tracking the currently selected note, do you mean that when a file is focused in a tab, it should automatically highlight its location in the folder list? Just want to make sure I understand your request correctly.

**Comment by tmargosiak** [comment]
Hi,

yes, that is what I meant - the file that is currently open should be highlighted in the list of files. That functionality has been added recently to the file explorer - https://obsidian.md/changelog/2025-01-22-desktop-v1.8.2/ - "Added a new File Explorer option to auto-reveal the active file."

In this case it shoul highlight both the file and the folder - as they are separated.

**Comment by XuQuan-nikkkki** [comment]
The track current note feature has been implemented in version 0.2.4 — feel free to let me know if you run into any issues with it. As for folder note support, that’s still on my list and will be added in a future version.

**Comment by tmargosiak** [comment]
Hi, thanks for that, for some reason it stopped working... In most cases clicking on a folder doesn't update the list of files. Sometimes it does work - I'm trying to figure out if there's any pattern for that.

Apart from that - it would also be good if the auto-selected file and folder would scroll into the view.

**Comment by XuQuan-nikkkki** [comment]
Thanks for the update. Just to clarify—when you mention “clicking on a folder doesn’t update the list of files,” do you mean the folder isn't being selected when clicked, or that it’s selected but the file list doesn't update accordingly? I’d like to make sure I’m understanding the behavior correctly.

**Comment by XuQuan-nikkkki** [comment]
Thanks for the feedback. I'm currently looking into the issue, but so far I haven't been able to reproduce it on my end.

Also, I just realized I forgot to update the version number in manifest.json when I released the latest version. I'm not sure if that might have caused Obsidian to load an outdated version of the plugin.

If it's not too much trouble, could you try downloading the latest main.js, manifest.json, and styles.css files directly from the [release page](https://github.com/XuQuan-nikkkki/FolderFile-Splitter-Plugin/releases), and manually replace the files in your vault’s .obsidian/plugins/folder-file-splitter folder? Let me know if the issue still happens after that, and I’ll continue looking into it.

**Comment by tmargosiak** [comment]
Hi, it still doesn't work after manual update. I can try to debug it if you let me know where to start.

**Comment by tmargosiak** [comment]
One more thing I've just noticed - in some cases after I click on a folder a different one is selected and shown.

**Comment by XuQuan-nikkkki** [comment]
Thanks for the detailed description. From what you described, it seems the issue might be that the folder you clicked and the folder the plugin thinks is focused are not consistent. I’d like to confirm if that’s the case.

If you're okay with it, could you try adding two console.log() statements in your `main.js to` help capture the problem?

### Steps:
1. Log the folder being clicked
    - Search for this line: `ref: setDropRef,`
    - Then find the onClick handler just below. It should look like this: `onClick: () => setFocusedFolder(folder)`
    - Replace it with:
```
onClick: () => {
  console.log("clicked path:", folder.path);
  setFocusedFolder(folder);
}
```

2. Log the folder used when updating the file list
    - Search for this line: `setFiles(defaultFiles);`
    - Add this above or below it: `console.log("focused folder:", focusedFolder?.path);`

After that, if you run into the issue again, please copy the console output and send it here. That will help confirm whether it's a state mismatch or something else.

Let me know if anything is unclear.

**Comment by tmargosiak** [comment]
Hi,

I've added additional logging and what I've observed:
1. if I click on a folder that doesn't work - I don't see anything in logs.
2. if I click on a folder and it works - then both the "clicked path" and "focused folder" messages are same.
3. in case I click on a folder e.g. 'X' and folder 'Y' is displayed, I see only "focused folder: Y". I also think that this happens right after Obsidian starts, I wasn't able to reproduce it later

**Comment by XuQuan-nikkkki** [comment]
Thanks for the follow-up.

Regarding point 3, the plugin now restores the previously opened folder and focused file immediately after it's ready. However, this state is stored internally by the plugin. If you're using both this plugin and the native file explorer, their last opened folders might not be in sync. I'm wondering if this mismatch is what led to the confusion you observed.

As for point 1, could you let me know which theme you're using? Also, do you have any custom CSS snippets enabled? I’d like to check if the clickable area is being affected by styles, potentially causing a mismatch between the visible region and where the click event is actually registered.

One way to help debug this:
In your `styles.css`, try searching for `.ffs__folder-container` and temporarily add this rule: `border: 1px solid red;`
This will make the clickable area visible. If you do this and try clicking again, please check whether the click only fails when it's outside the red box.

Let me know what you find.

**Comment by tmargosiak** [comment]
Hi,

I've noticed some exceptions when I was testing the plugin and it turned out that they were caused by the FolderNote plugin. When I disabled it everything seems to work okay!

Answering your quesions - I don't have any custom theme or css. As for the point #3 - I will test it, as after disabling the FolderNote it seems to be gone. I'll let you know.

**Comment by XuQuan-nikkkki** [comment]
Could you share the exact exception message you’re seeing? That would help narrow down what’s going wrong.
